version: '3'

services:
  app:
    image: 'nginx:1.12-alpine'
    ports:
      - '8082:80'
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - './dist:/srv/app/web:ro'
  base:
    build: .
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: /bin/sh -c "yarn install && yarn build:client:en && yarn build:client:bg"
  i18n:
    build: .
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: /bin/sh -c "yarn install && yarn xi18n"
  dev_run:
    build: .
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: /bin/sh -c "yarn install && yarn start"
